/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.usuariosGUI;

//Importando módulos necesarios...
import sistema.usuariosDAL.conexion;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sistema.usuariosBL.usuarioBL;


/**
 *
 * @author Alex Gabriel Santiago Gonzalez :D
 */
public class frmUsuarios extends javax.swing.JFrame{
    DefaultTableModel modelo;
    /**
     * Creates new form frmUsuarios
     */
    //Método constructor
    public frmUsuarios() {
        initComponents();
        //Estableciendo las columnas que tendra mi tabla.
        String[] titulos = {"ID","Usuario","Nombre","Apellido","Teléfono","Correo Electronico"};
        modelo = new DefaultTableModel(null,titulos);
        tblUsuarios.setModel(modelo);
        //Cargando los datos en mi tabla para que puedan ser mostrados al usuario.
        this.mostrarDataos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        bttActualizarTabla = new javax.swing.JButton();
        bttActualizar = new javax.swing.JButton();
        bttEliminar = new javax.swing.JButton();
        bttCerrarSeccion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bttCancelar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsuarios);

        bttActualizarTabla.setText("Actualizar tabla");
        bttActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttActualizarTablaActionPerformed(evt);
            }
        });

        bttActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/actualizar.png"))); // NOI18N
        bttActualizar.setText("Actualizar");
        bttActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttActualizarActionPerformed(evt);
            }
        });

        bttEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/boton-eliminar.png"))); // NOI18N
        bttEliminar.setText("Eliminar");
        bttEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminarActionPerformed(evt);
            }
        });

        bttCerrarSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/log-out.png"))); // NOI18N
        bttCerrarSeccion.setText("Cerrar Sección");
        bttCerrarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCerrarSeccionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Usuarios Registrados:");

        bttCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/Cancelar.png"))); // NOI18N
        bttCancelar.setText("Cancelar");
        bttCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarActionPerformed(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/userInfo.png"))); // NOI18N
        jLabel2.setText("Datos Del Usuario");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Teléfono:");

        jLabel6.setText("Correo Electronico:");

        txtID.setEditable(false);

        jLabel7.setText("ID Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(137, 137, 137))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre)
                                            .addComponent(txtTelefono))))
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellido)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttActualizarTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttActualizar)
                        .addGap(29, 29, 29)
                        .addComponent(bttEliminar)
                        .addGap(46, 46, 46)
                        .addComponent(bttCancelar)
                        .addGap(51, 51, 51)
                        .addComponent(bttCerrarSeccion)))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel2)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttActualizarTabla)
                    .addComponent(bttActualizar)
                    .addComponent(bttEliminar)
                    .addComponent(bttCancelar)
                    .addComponent(bttCerrarSeccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Método para eliminar un registro de la tabla usuario dependiendo del ID que contenga el usuario seleccionado...
    private void bttEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminarActionPerformed
        // TODO add your handling code here:
        
        //Estableciendo conexión con mi Base De Datos sistema.
        conexion objConexion= new conexion();
        //Recuperando los datos.
        usuarioBL oUsuarios= recuperarDatosGUI();
        //Estableciendo mi sentencia DELETE para poder borrar los registros que contenga mi tabla usuario.
        String strSentenciaInsert= String.format("DELETE FROM usuario WHERE idusuario = %d",oUsuarios.getIdusuario());
        //Ejecutando sentencia...
        objConexion.ejecutarSentenciaMYSQL(strSentenciaInsert);
        //Actualizando tabla para que cargue nuevamente los registros.
        this.mostrarDataos();
        //Limpiando mis txtFields.
        this.limpiar();
        
        
        
    }//GEN-LAST:event_bttEliminarActionPerformed
    //Método para actualizar un registro mi tabla usuario...
    private void bttActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttActualizarActionPerformed
        // TODO add your handling code here:
        
        //Estableciendo conexión con mi base de datos sistema.
        conexion objConexion= new conexion();
         //Recuperando los datos.
        usuarioBL oUsuarios= recuperarDatosGUI();
        //Estableciendo mi sentencia UPDATE para poder actualizar algún registro que contenga mi tabla usuario.
        String strSentenciaInsert= String.format("UPDATE usuario SET nombre ='%s', apellido = '%s', telefono = '%s', correo_electronico = '%s' WHERE idusuario = %d",oUsuarios.getNombre(),oUsuarios.getApellido(),oUsuarios.getTelefono(),oUsuarios.getCorreo_electronico(), oUsuarios.getIdusuario());
        //Ejecutando sentencia...
        objConexion.ejecutarSentenciaMYSQL(strSentenciaInsert);
        //Actualizando tabla para que cargue nuevamente los registros.
        this.mostrarDataos();
        //Limpiando mis txtFields.
        this.limpiar();
        
    }//GEN-LAST:event_bttActualizarActionPerformed
    //Método para actualizar mi tabla (cargar los registros nuevamente).
    private void bttActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttActualizarTablaActionPerformed
        // TODO add your handling code here:
        //Actualizando tabla para que cargue nuevamente los registros.
        this.mostrarDataos();
    }//GEN-LAST:event_bttActualizarTablaActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed
    //Método para tomar los registros (En mi tabla del programa) para llevarlos automaticamente con un click, hacia mi txt fields.
    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            
            JTable receptor= (JTable) evt.getSource();
            
            txtID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString() );
            txtNombre.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString() );
            txtApellido.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),3).toString() );
            txtTelefono.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),4).toString() );
            txtCorreo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),5).toString() );
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked
    //Método para limpiar mis txtFields utilizando el botón que se muestra en el programa llamado "Cancelar".
    private void bttCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarActionPerformed
        // TODO add your handling code here:
        
        this.limpiar();
    }//GEN-LAST:event_bttCancelarActionPerformed
    //Método para cerrar sección y volver hacia mi menú de login.
    private void bttCerrarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCerrarSeccionActionPerformed
        // TODO add your handling code here:
        
        loginUsuarios.L.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_bttCerrarSeccionActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed
    //Método para mostrar los datos en forma de registro en mi tabla de forma automatica.
    public void mostrarDataos(){
        //Preprando mis registros en mi tabla...
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        //Estableciendo conexión en mi base de datos.
        conexion objConexion= new conexion();
        //Try catch para el manejo de posibles errores.
          try {
            //Realizando consulta para traer todos los registros que esten en mi tabla usuario de mi base de datos sistema.
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM usuario");
            //Tomando todos los registros y guardandolo en un object para luego mostarlos en mi tabla del programa...
            while (resultado.next()) {
                System.out.println(resultado.getString("idusuario"));
                System.out.println(resultado.getString("usuario"));
                System.out.println(resultado.getString("nombre"));
                System.out.println(resultado.getString("apellido"));
                System.out.println(resultado.getString("telefono"));
                System.out.println(resultado.getString("Correo_Electronico"));
                Object[] oUsuario={resultado.getString("idusuario"),resultado.getString("usuario"),resultado.getString("nombre"),resultado.getString("apellido"),resultado.getString("telefono"),resultado.getString("Correo_Electronico") };
                modelo.addRow(oUsuario);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
    }
    //Método para establecerle los valores a mis atributos establecidos en mi clase usuarioBL, utilizando los datos que se ingresaron en mis txtFields
    public usuarioBL recuperarDatosGUI(){
        usuarioBL oUsuarios= new usuarioBL();
        
        int id = (txtID.getText().isEmpty())?0: Integer.parseInt(txtID.getText());
        
        oUsuarios.setIdusuario(id);
        oUsuarios.setNombre(txtNombre.getText());
        oUsuarios.setApellido(txtApellido.getText());
        oUsuarios.setTelefono(txtTelefono.getText());
        oUsuarios.setCorreo_electronico(txtCorreo.getText());
        
        return oUsuarios;
    }
    //Método para limpiar los datos que contengan escritos mis txtFields.
    public void limpiar(){
    
        txtID.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttActualizar;
    private javax.swing.JButton bttActualizarTabla;
    private javax.swing.JButton bttCancelar;
    private javax.swing.JButton bttCerrarSeccion;
    private javax.swing.JButton bttEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
